#!/usr/bin/python
import sys,os
delta = "0.025"
for i in [4,5]:
	#os.system('./gen-accumulation-reduction-formula2 '+str(i)+' ' + delta +' | sed \"s/\\"//g\" | tee ../examples/fml/assoc-'+str(i)+'-'+str(delta)+'.fml')
	os.system('./gen-accumulation-reduction-formula2 '+str(i)+' ' + delta +' | sed \"s/\\"//g\" | tee ../examples/fml/assoc-'+str(i)+'-'+delta+'.fml')
