#!/usr/bin/python
import sys,os
#delta='0.025'
low = 5
high = 65
step = 5
index = low
while index <= high:
	os.system('./gen-accumulation-reduction-z3-ijcar '+str(index)+' | sed \"s/\\"//g\" | tee ../examples/z3-ijcar/smtlib/z3-ijcar-assoc-'+str(index)+'.smt2')
	index = index + step
